// Code generated by "stringer -type=ChType"; DO NOT EDIT.

package chutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Int-1]
	_ = x[String-2]
	_ = x[FixedString-3]
	_ = x[Float-4]
}

const _ChType_name = "UnknownIntStringFixedStringFloat"

var _ChType_index = [...]uint8{0, 7, 10, 16, 27, 32}

func (i ChType) String() string {
	if i < 0 || i >= ChType(len(_ChType_index)-1) {
		return "ChType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChType_name[_ChType_index[i]:_ChType_index[i+1]]
}
