// Code generated by "stringer -type=ErrType"; DO NOT EDIT.

package chutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown-0]
	_ = x[ErrInput-1]
	_ = x[ErrOutput-2]
	_ = x[ErrFields-3]
	_ = x[ErrFieldCount-4]
	_ = x[ErrDateFormat-5]
	_ = x[ErrSeek-6]
	_ = x[ErrRWNum-7]
	_ = x[ErrStr-8]
}

const _ErrType_name = "ErrUnknownErrInputErrOutputErrFieldsErrFieldCountErrDateFormatErrSeekErrRWNumErrStr"

var _ErrType_index = [...]uint8{0, 10, 18, 27, 36, 49, 62, 69, 77, 83}

func (i ErrType) String() string {
	if i < 0 || i >= ErrType(len(_ErrType_index)-1) {
		return "ErrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrType_name[_ErrType_index[i]:_ErrType_index[i+1]]
}
