// Code generated by "stringer -type=FileFormat"; DO NOT EDIT.

package chutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CSV-0]
	_ = x[CSVWithNames-1]
	_ = x[TabSeparated-2]
}

const _FileFormat_name = "CSVCSVWithNamesTabSeparated"

var _FileFormat_index = [...]uint8{0, 3, 15, 27}

func (i FileFormat) String() string {
	if i < 0 || i >= FileFormat(len(_FileFormat_index)-1) {
		return "FileFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileFormat_name[_FileFormat_index[i]:_FileFormat_index[i+1]]
}
