// Code generated by "stringer -type=Status"; DO NOT EDIT.

package chutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pass-0]
	_ = x[ValueFail-1]
	_ = x[TypeFail-2]
	_ = x[Calculated-3]
	_ = x[Pending-4]
}

const _Status_name = "PassValueFailTypeFailCalculatedPending"

var _Status_index = [...]uint8{0, 4, 13, 21, 31, 38}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
